### ISSUE TITLE
gsutil module 'sys' has no attribute 'maxint'

### ISSUE THREAD

**Issue by a2x** [GoogleCloudPlatform/gsutil#1427]
on several machines, by default cloud cli installation, on macOS 12.0.1 (python 2.7.18 and 3.8.9 installed) and gsutil v 5.5

Command: gsutil -m rsync -r ... ...
runs into 
gsutil module 'sys' has no attribute 'maxint'

if it requires crcmod or whatever, a mention in the cli install process would be a huge time and pain saver. 
Thx

**Comment by thomasmaclean** [comment]
The notice to users is duly noted, but I believe this is due to a temporary issue in Cloud SDK.

There's a known issue with the bundled python in 365.0.0 that was fixed in the latest version (366.0.0). You can fix this issue temporarily by running `export CLOUDSDK_PYTHON=$(which python3)` which should get you back on the system Python where you can install `crcmod` locally. You can shut this workaround off by running `unset CLOUDSDK_PYTHON`.

**Comment by mlimbuu** [comment]
this didnt fixed my issue in Mac M1. Any suggestion beside downgrading python3 to python2?

**Comment by mbyrne00** [comment]
`pip3 install -U crcmod` did work on my M1 mac

**Comment by christoph-meier-offerup** [comment]
Still have this issue. The above tips with crcmod didn't fix anything,

**Comment by dcsan** [comment]
2023 and this is still an issue. thanks for the tips above guys!

**Comment by paulhtremblay** [comment]
pip install did not fix issue. This is not July 2023! Good grief

**Comment by mbyrne00** [comment]
Actually ... it _is_ July 2023 😉. 

Did you try `pip3 install` if you are on a mac? Only advice I have to offer on it, sorry as that worked for mine.

**Comment by paulhtremblay** [comment]
Yes, I tried pip install, and that did not fix the issue. I even went into the source code and changed maxint to maxsize, but then another bug appeared. So I will make my own rsync

**Comment by hulius** [comment]
If `pip3 install` is not working, it may be because it is not installing the right version (you may have multiple Python version installed).

To force it to use the version used by gsutil :

1. Run `gcloud info`
2. Note down the `Python Location`
3. Run `<python_location> -m pip install crcmod`.
    In my case it was `/opt/homebrew/bin/python3 -m pip install crcmod`

And then it worked for me!

Instructions copied from: https://github.com/GoogleCloudPlatform/gsutil/issues/1052#issuecomment-1377798556

**Comment by evil-shrike** [comment]
Any chance to get it fixed without any additional exercises? I want to understand how reliable to put `gsutil rsync` in my installation scripts.

**Comment by SamGallagher95** [comment]
Bumping that it's August 2023 with the same issue. Luckily the pip install method worked for my M1 Mac

**Comment by jillesvangurp** [comment]
I had the added complication that for some reason after some updates, gsutil now uses my miniconda installation. Which had no pip for some reason. And pip/pip3 point to the homebrew install. What a mess. Worked a few weeks ago and somehow broke with the latest homebrew update. I did not touch conda in between. Also `gcloud components update` did not cause this (or fix it, I tried).

So, had to do this to fix it:

```bash
conda install pip
# this would be the python
python -m pip install crcmod
```

Can somebody just sort out gcloud dependencies on python? It using whatever python seems like that shouldn't happen. Nice that it works with conda as well. But it should probably not rely on any system defaults for python or global python packages like this one. I would expect it to have its own bloody venv with everything it needs and a bundled python that works. I think it used to work like that?!
