### ISSUE TITLE
setmeta -h "<string with space>" doesn't work

### ISSUE THREAD

**Issue by haraldschilly** [GoogleCloudPlatform/gsutil#266]
I'm using a GCE ubuntu 14.10 box, created yesterday, and running gsutil as it comes from GCE. 

Turns out, this doesn't work:

```
gsutil setmeta -h "Cache-Control:public, max-age=600" gs://<bucket>/**
```

Error:

```
CommandException: No URLs matched: max-age=600
```

Which suggests to me that the space between "...public, max-age..." in the quotes for setting the header is not properly quoted when going through the argument parser of that python script in the background.
Without the space, it works.

Your [documentation](https://cloud.google.com/storage/docs/gsutil/commands/setmeta) indeed mentions 

```
-h "Cache-Control:public, max-age=3600"
```

explicitly, so I am pretty sure I'm using it correctly ;-)

**Comment by thobrla** [comment]
Hello,

Can you add the output of "gsutil version -l" to this issue?  I tried this with the current version (4.11) and could not reproduce the issue, which leads me to believe this is a problem with an older version of gsutil.

**Comment by haraldschilly** [comment]
Well, that could be the case, it's an older one. I don't know how it ends up in those GCE instances, I'll try to update it with it's update utility ... that should fix it, I guess.

```
$ gsutil version -l
gsutil version: 4.6
checksum: 397d8391fddbf1c48cc31f9c2911be68 (!= 70858e3360112a908c76273e6c947098)
boto version: 2.30.0
python version: 2.7.8 (default, Oct 20 2014, 15:05:19) [GCC 4.9.1]
OS: Linux 3.16.0-34-generic
multiprocessing available: True
using cloud sdk: True
config path: /etc/boto.cfg
gsutil path: /usr/lib/google-cloud-sdk/platform/gsutil/gsutil
compiled crcmod: True
installed via package manager: False
editable install: False
```

**Comment by haraldschilly** [comment]
Ah, ok, well, I guess I have to install this gcloud thing separately. Sorry, I'm a bit a GCE noob ;-)

```
<name@host>:~$ sudo gsutil update
It looks like you are trying to run "/usr/lib/google-cloud-sdk/bin/bootstrapping/gsutil.py update".
The "update" command is no longer needed with the Cloud SDK.
To update, run: gcloud components update
Really run this command? (y/N) n

<name@host>:~$ sudo gcloud components update
You cannot perform this action because the component manager has been 
disabled for this installation.  If you would like get the latest 
version of the Google Cloud SDK, please see our main download page at:
  https://developers.google.com/cloud/sdk/
ERROR: (gcloud.components.update) The component manager is disabled for this installation
```

**Comment by adilroot** [comment]
having the same issue, I have deployed ubuntu-1504 on GCE 

I noticed that gcloud components update retuns this error
```
name@ubuntu1504:~$  gcloud components update
You cannot perform this action because the component manager has been 
disabled for this installation.  If you would like get the latest 
version of the Google Cloud SDK, please see our main download page at:

  https://developers.google.com/cloud/sdk/

ERROR: (gcloud.components.update) The component manager is disabled for this installation
```

PS: On centos-7 GCE instance the `gcloud components update` works without any issue.

**Comment by ZE3kr** [comment]
I also have the same issue:

```bash
$ gsutil setmeta -h "Cache-Control:public, max-age=31536000" gs://bucket/index.html
CommandException: No URLs matched: max-age=31536000
```

**Comment by ZE3kr** [comment]
And the version:

```
$ gsutil version -l
gsutil version: 4.19
checksum: 67da5fbdef140f1663fbb11e96bb9f90 (OK)
boto version: 2.39.0
python version: 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
OS: Linux 4.4.0-62-generic
multiprocessing available: True
using cloud sdk: True
config path: /etc/boto.cfg
gsutil path: /usr/lib/google-cloud-sdk/platform/gsutil/gsutil
compiled crcmod: False
installed via package manager: False
editable install: False
```

**Comment by ZE3kr** [comment]
And I just updated to the newest version(4.22), still not work

**Comment by ZE3kr** [comment]
I tried this command, and it works:
```
/usr/lib/google-cloud-sdk/bin/gsutil setmeta -h "Cache-Control:public, max-age=31536000" gs://bucket/index.html
```

however, both of then return gsutil version: 4.22

And I do this, then it work:

```
$ rm /usr/bin/gsutil
$ ln -s /usr/lib/google-cloud-sdk/bin/gsutil /usr/bin/gsutil
```

**Comment by houglum** [comment]
This looks like an error in the gsutil wrapper script present on GCE instances (located at /usr/bin/gsutil):

`exec /usr/lib/google-cloud-sdk/bin/gsutil ${@}`

Note that the positional parameters with spaces in them will "dissolve" into separate parameters because `${@}` was used instead of `"${@}"`.  I'll notify the GCE folks responsible for maintaining the wrapper script.  Thanks for finding this!

Invoking gsutil directly (which is essentially what your `ln` solution did) should work until they get this fixed.

**Comment by houglum** [comment]
Just an FYI: This seems to be a bug in the Ubuntu images for GCE.  After creating several different VM types (Debian 8, CentOS 7, and Ubuntu 14.04), only the Ubuntu VM had this old version of the gsutil wrapper script.  New VMs using other images should have an updated version of the wrapper script that works correctly.

**Comment by ZE3kr** [comment]
@houglum Correct, I'm using the official image Ubuntu 16.04 on GCE.

**Comment by houglum** [comment]
Thanks for the confirmation. Our GCE folks are working to get this fixed :)

**Comment by houglum** [comment]
@ZE3kr, this is fixed in our newest Ubuntu images.
